apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'com.levin197.mobileapp01'
version = '1.0.0'

android {
  namespace 'com.levin197.mobileapp01.screencapture'
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
  lintOptions {
    abortOnError false
  }
}
